<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>


<div class="page-header" >
    <h1>Goods</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Img</th>
            <th>Type</th>
            <th>Category</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $good): ?>
            <tr>
                <td><?php echo $good->id_good ?></td>
            <td><?php echo $good->name ?></td>
            <td style = "text-align:center;" ><?php echo $this->tag->imageInput([
                    "src" => "/public/img/".$good->img,
                    "style" => "width: 70%;"
                ])?></td>
            <td><?php echo $good->goodTypes->name ?></td>
            <td><?php
                $categories = [];
                foreach($good->goodCategory as $goodCategory){
                    $categories[] = $goodCategory->categories->name;
                }
                echo implode(', ', $categories); ?>
            </td>

            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("goods/index", "First") ?></li>
                <li><?php echo $this->tag->linkTo("goods/index?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("goods/index?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("goods/index?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
