<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search goods
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["goods/new", "Create goods"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "goods/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>



<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldImg" class="col-sm-2 control-label">Img</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["img", "size" => 30, "class" => "form-control", "id" => "fieldImg"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdGoodType" class="col-sm-2 control-label">Id Of Good Of Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_good_type", "type" => "number", "class" => "form-control", "id" => "fieldIdGoodType"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
